//------------------------------------------------------------------------------
// <auto-generated>
// Code auto-generated by CategoryGenerator version 0.0.0.
// Re-run the generator every time the Logger needs to be updated.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace MessageLogger.Editor
{
    internal class CharacterCategory : MessageCategory
    {
        protected override void Subscribe()
        {
            var instance = DeeDeeR.MessageBroker.MessageBroker.Instance.Character;
            instance.OnCharacterCreated += Handle_OnCharacterCreated;
        }

        protected override void Unsubscribe()
        {
            var instance = DeeDeeR.MessageBroker.MessageBroker.Instance.Character;
            instance.OnCharacterCreated -= Handle_OnCharacterCreated;
        }

        private void Handle_OnCharacterCreated(object sender, DeeDeeR.MessageBroker.CharacterCreatedEventArgs e)
        {
            Logger.LogEvent(e);
        }
    }
}