//------------------------------------------------------------------------------
// <auto-generated>
// Code auto-generated by CategoryGenerator version 0.0.0.
// Re-run the generator every time the Logger needs to be updated.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace MessageLogger.Editor
{
    internal class LoggerCategory : MessageCategory
    {
        protected override void Subscribe()
        {
            var instance = DeeDeeR.MessageBroker.MessageBroker.Instance.Logger;
            instance.OnLog += Handle_OnLog;
            instance.OnLogException += Handle_OnLogException;
        }

        protected override void Unsubscribe()
        {
            var instance = DeeDeeR.MessageBroker.MessageBroker.Instance.Logger;
            instance.OnLog -= Handle_OnLog;
            instance.OnLogException -= Handle_OnLogException;
        }

        private void Handle_OnLog(object sender, DeeDeeR.MessageBroker.LogEventArgs e)
        {
            Logger.LogEvent(e);
        }

        private void Handle_OnLogException(object sender, DeeDeeR.MessageBroker.LogExceptionEventArgs e)
        {
            Logger.LogEvent(e);
        }
    }
}