//------------------------------------------------------------------------------
// <auto-generated>
// Code auto-generated by MessageBrokerGenerator version <version undefined>.
// Re-run the generator every time a new Message is added or removed.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using UnityEngine;
using UnityEditor;

namespace DeeDeeR.MessageBroker
{
	/// <summary>
	/// MessageBroker publisher for Character category.
	/// </summary>
	 public class MBCharacter2
	{
		#region Event declaration

		/// <summary>
		/// 
		/// </summary>
		public event Action<object, object, DnD.Code.Scripts.Characters.CharacterStats> CharacterCreated;

		#endregion

		#region Send methods

		/// <summary>
		/// Send a message of type CharacterCreated.
		/// <param name="sender">The sender of the message. Required.</param>
		/// <param name="target">The target of the message. Optional.</param>
		/// <param name="characterStatsInstance"></param>
		/// </summary>
		public void Send_CharacterCreated(object sender, object target, DnD.Code.Scripts.Characters.CharacterStats characterStatsInstance)
		{
			if (sender == null)
			{
				Debug.LogError("sender is required.");
				return;
			}

			CharacterCreated?.Invoke(sender, target, characterStatsInstance);
		}

		#endregion

	}
}
