//------------------------------------------------------------------------------
// <auto-generated>
// Code auto-generated by MessageBrokerGenerator
// Re-run the generator every time a new Message is added or removed.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;

namespace DeeDeeR.MessageBroker
{
	/// <summary>
	/// Message Broker component exposing methods to send messages defined as ScriptableObjects of type <see cref="Message"/>.
	/// </summary>
	[AddComponentMenu("DeeDeeR/Message Broker/Message Broker")]
	public sealed partial class MessageBroker : MonoBehaviour, IMessageBroker
	{
		/// <inheritdoc/>
		public MBGame Game { get; } = new MBGame();

		/// <inheritdoc/>
		public MBMenus Menus { get; } = new MBMenus();

	}
}
