//------------------------------------------------------------------------------
// <auto-generated>
// Code auto-generated by MessageBrokerGenerator version <version undefined>.
// Re-run the generator every time a new Message is added or removed.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using UnityEngine;
using UnityEditor;

namespace DeeDeeR.MessageBroker
{
	/// <summary>
	/// MessageBroker publisher for Logger category.
	/// </summary>
	 public class MBLogger2
	{
		#region Event declaration

		/// <summary>
		/// 
		/// </summary>
		public event Action<object, object, string, UnityEngine.LogType> Log;

		#endregion

		#region Send methods

		/// <summary>
		/// Send a message of type Log.
		/// <param name="sender">The sender of the message. Required.</param>
		/// <param name="target">The target of the message. Optional.</param>
		/// <param name="message"></param>
		/// <param name="logLevel"></param>
		/// </summary>
		public void Send_Log(object sender, object target, string message, UnityEngine.LogType logLevel)
		{
			if (sender == null)
			{
				Debug.LogError("sender is required.");
				return;
			}

			Log?.Invoke(sender, target, message, logLevel);
		}

		#endregion

	}
}
