//------------------------------------------------------------------------------
// <auto-generated>
// Code auto-generated by CategoryGenerator version <version undefined>.
// Re-run the generator every time a new Message is added or removed.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using UnityEditor;
using MessageBroker;

namespace DeeDeeR.MessageBroker
{
    /// <summary>
    /// 
    /// </summary>
    public class MBGame
    {
        /// <summary>
        /// 
        /// </summary>
        public event EventHandler<MessageBrokerEventArgs> OnGameOver;
        /// <summary>
        /// 
        /// </summary>
        public event EventHandler<MessageBrokerEventArgs> OnGamePaused;
        /// <summary>
        /// 
        /// </summary>
        public event EventHandler<MessageBrokerEventArgs> OnGameResumed;
        /// <summary>
        /// 
        /// </summary>
        public event EventHandler<MessageBrokerEventArgs> OnGameStarted;
        /// <summary>
        /// 
        /// </summary>
        public void Send_OnGameOver(object sender, object target)
        {
            if (sender == null)
            {
                var errorEventArgs = Common.CreateArgumentNullExceptionEventArgs("Game", target, "sender");
                DeeDeeR.MessageBroker.MessageBroker.Instance.Logger.Send_OnLogException(sender, target, errorEventArgs);
                return;
            }

            if (target == null)
            {
                var errorEventArgs = Common.CreateArgumentNullExceptionEventArgs("Game", target, "target");
                DeeDeeR.MessageBroker.MessageBroker.Instance.Logger.Send_OnLogException(sender, target, errorEventArgs);
                return;
            }

            var __eventArgs__ = MessageBrokerEventArgs.Pool<MessageBrokerEventArgs>.Rent();
            __eventArgs__.Sender = sender;
            __eventArgs__.Target = target;
            OnGameOver?.Invoke(sender, __eventArgs__);
        }

        /// <summary>
        /// 
        /// </summary>
        public void Send_OnGamePaused(object sender, object target)
        {
            if (sender == null)
            {
                var errorEventArgs = Common.CreateArgumentNullExceptionEventArgs("Game", target, "sender");
                DeeDeeR.MessageBroker.MessageBroker.Instance.Logger.Send_OnLogException(sender, target, errorEventArgs);
                return;
            }

            if (target == null)
            {
                var errorEventArgs = Common.CreateArgumentNullExceptionEventArgs("Game", target, "target");
                DeeDeeR.MessageBroker.MessageBroker.Instance.Logger.Send_OnLogException(sender, target, errorEventArgs);
                return;
            }

            var __eventArgs__ = MessageBrokerEventArgs.Pool<MessageBrokerEventArgs>.Rent();
            __eventArgs__.Sender = sender;
            __eventArgs__.Target = target;
            OnGamePaused?.Invoke(sender, __eventArgs__);
        }

        /// <summary>
        /// 
        /// </summary>
        public void Send_OnGameResumed(object sender, object target)
        {
            if (sender == null)
            {
                var errorEventArgs = Common.CreateArgumentNullExceptionEventArgs("Game", target, "sender");
                DeeDeeR.MessageBroker.MessageBroker.Instance.Logger.Send_OnLogException(sender, target, errorEventArgs);
                return;
            }

            if (target == null)
            {
                var errorEventArgs = Common.CreateArgumentNullExceptionEventArgs("Game", target, "target");
                DeeDeeR.MessageBroker.MessageBroker.Instance.Logger.Send_OnLogException(sender, target, errorEventArgs);
                return;
            }

            var __eventArgs__ = MessageBrokerEventArgs.Pool<MessageBrokerEventArgs>.Rent();
            __eventArgs__.Sender = sender;
            __eventArgs__.Target = target;
            OnGameResumed?.Invoke(sender, __eventArgs__);
        }

        /// <summary>
        /// 
        /// </summary>
        public void Send_OnGameStarted(object sender, object target)
        {
            if (sender == null)
            {
                var errorEventArgs = Common.CreateArgumentNullExceptionEventArgs("Game", target, "sender");
                DeeDeeR.MessageBroker.MessageBroker.Instance.Logger.Send_OnLogException(sender, target, errorEventArgs);
                return;
            }

            if (target == null)
            {
                var errorEventArgs = Common.CreateArgumentNullExceptionEventArgs("Game", target, "target");
                DeeDeeR.MessageBroker.MessageBroker.Instance.Logger.Send_OnLogException(sender, target, errorEventArgs);
                return;
            }

            var __eventArgs__ = MessageBrokerEventArgs.Pool<MessageBrokerEventArgs>.Rent();
            __eventArgs__.Sender = sender;
            __eventArgs__.Target = target;
            OnGameStarted?.Invoke(sender, __eventArgs__);
        }
    }
}